# Generated by Django 2.2 on 2021-08-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('manager', models.CharField(max_length=20)),
                ('maxCapacity', models.IntegerField()),
                ('currentAmount', models.IntegerField()),
                ('checkInTime', models.DateTimeField(auto_now_add=True)),
                ('checkOutTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
