# Generated by Django 2.2 on 2021-08-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oniet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currentAmount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='maxCapacity',
            field=models.PositiveIntegerField(),
        ),
    ]
